### ISSUE TITLE
Có thể nhầm giữa việc chia tập huấn luyện và kiểm tra phần ví dụ trang 123

### ISSUE THREAD

**Issue by nvty13** [tiepvupsu/ebookMLCB#1]
Em chào anh Tiệp, 
Em đang đọc quyển Machine Learning Cơ bản của anh, ở trang 123 anh có viết:

> Tiếp theo, **130 mẫu dữ liệu được lấy ra ngẫu nhiên tạo thành tập huấn luyện**, **20 mẫu còn lại được dùng để kiểm tra**.

  
```
print(’Labels:’, np.unique(iris_y))
# split train and test
np.random.seed(7)
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=130)

print(’Training size:’, X_train.shape[0], ’, test size:’, X_test.shape[0])
```
Nhưng khi in ra lại ngược lại, em không biết đây có phải là do anh viết nhầm hay do em hiểu sai

```
Labels: [0 1 2]
Training size: 20 , test size: 130
```

Cám ơn anh rất nhiều.

**Comment by tiepvupsu** [comment]
Cảm ơn em. Có vẻ là anh đã viết ngược. Đúng phải là 130 mẫu kiểm tra, 20 mẫu huấn luyện. Anh sẽ sửa lỗi này vào cuối tuần.
