### ISSUE TITLE
Lỗi chính tả và đánh máy

### ISSUE THREAD

**Issue by Typhoon1089** [tiepvupsu/ebookMLCB#3]
Dưới đây là các lỗi mình ghi lại được từ bản in. Tiệp thấy lỗi nào đã sửa rồi thì bỏ qua nhé.
- Trang 48: Mục lục 2.4.5 bị đẩy dòng
- Trang 61: hiep => hiệp trong "3.1.9 Ma trận hiệp phương sai"
- Trang 146: NCB => NBC
- Trang 149: Hình 11.1 dấu bằng ở "2/3(4/20)^2" có vẻ không chính xác. Đổi chỗ với dấu xấp xỉ có vẻ chuẩn hơn?
- Trang 176: o.w. => trường hợp còn lại
- Trang 198: ove => one
- Trang 205: "c=max_i z_i" => c = max z_i
- Trang 270: Có nhiều dấu = ở "Không âm và giảm dần"

Khác
- Trang 76: Hình 4.1 có 2 đường cùng nét liền. Hình này không rõ trục tung
- Trang 110: chú thích số 23 để không hợp lý trong bản in, dễ hiểu nhầm thành 0^23.
- Hình 14.2 nên nới dài ra một chút.
- Trang 214: Từ biểu diễn nên cho vào ngoặc kép. Mặc dù, mình không tìm được từ nào hay hơn :)

**Comment by tiepvupsu** [comment]
Cảm ơn bạn,
Mình đã sửa hầu hết các lỗi, trừ:

* Trang 149 đúng là dấu bằng, dấu thứ hai mới là dấu xấp xỉ.
* Trang 270, có nhiều dấu bằng không có gì lạ thường, vì đằng sau đó có nhiều trị riêng bằng 0. Mình thấy có thừa một dấu phẩy nên đã bỏ đi.

Các phần trong mục "Khác" sẽ được chuyển sang một issue khác.

**Comment by Typhoon1089** [comment]
> Trang 149 đúng là dấu bằng, dấu thứ hai mới là dấu xấp xỉ.

Oh, mình diễn tả không tốt lắm. Ý mình không nói về dấu xấp xỉ 1.5x10^(-4). 
Chính xác thì trong đoạn 
`p(B)\prod_{i=1}^{d} p(x_i|B) = \frac{3}{4} (\frac{4}{20})^2 \frac{2}{20} \frac{1}{20} \approx 1.5 \times 10^{-4}`, 
mình chưa thật hiểu dấu bằng duy nhất ở đây. Thật khó hiểu khi vế trái là tích của 9 số hạng `p(x_i|B)`.

Mong bạn giải thích `x_i` là gì và tại sao bạn dùng `prod_{i=1}^{d}`.
Hiện tại thì mình đang hiểu là `p(B|\text{d5}) \propto p(B) \prod_{j=1}^{4} \hat{\lambda}_B(\text{d5}_j)` (xin dùng https://www.codecogs.com/latex/eqneditor.php để xem cụ thê
