### ISSUE TITLE
Các điểm có thể làm rõ hơn

### ISSUE THREAD

**Issue by Typhoon1089** [tiepvupsu/ebookMLCB#4]
Có một vài chỗ nếu Tiệp có thể viết rõ ràng hơn thì sẽ tốt hơn
- Trang 70: không nên kí hiệu là x_i^j cho vị trí (i,j) vì dễ gây hiểu nhầm với số mũ.
- Trang 69: Có nên giả sử xác suất có dạng Bernoulli trước và ta đi tìm phân phối này không?
- Trang 75: "đây chính là bài toán tối ưu cho 4.38". Theo mình là 4.9 thì mới chính xác
- Trang 189: Chưa được rõ ý. Có nên nói ngay từ đầu ta sẽ đi tìm lý do tại sao hàm sigmoid được dùng nhiều nhất. Thay vì cuối cùng mới đưa ra.
- Trang 215: Có một câu hỏi là tại sao ta bỏ hết hệ số bias "b" tất cả neuron ra? Có lợi gì?
- Trang 223: Cùng chiều với vector thì có thể hiểu được. còn cùng chiều với ma trận là như thế nào?

**Comment by tiepvupsu** [comment]
Cảm ơn bạn, mình đã tách ra các issue và sẽ giải quyết từ từ:

#13, #14, #15, #16, #17, #18
