### ISSUE TITLE
Source Code trong bản pdf thiếu hoặc không thực hiện được

### ISSUE THREAD

**Issue by Typhoon1089** [tiepvupsu/ebookMLCB#5]
Tiệp check lại những điểm này nhé. Mình ghi lại lâu lâu rồi không rõ đã được sửa chưa
- Trang 135: hàm kmeans_display không tìm được
- MNIST hiện tại không download được bằng fetch_mldata, nên ghi chú là dùng  fetch_openml thay thế
- Trang 209-210: hàm pred(W, X) hình như không đầy đủ.
Dù sao thì cám ơn Tiệp vì đã bỏ công sức viết một cuốn sách tốt, có giá trị tra cứu rất tốt.

**Comment by tiepvupsu** [comment]
Cảm ơn bạn, mình đã tách ra các issue riêng và sẽ giải quyết từ từ.

#19, #20, #21
